name:               Stephanie Handsteiner
description:        Designer & Developer
meta_description:   "Stephanie Handsteiner – Designer & Developer"

aboutPage:          true
markdown:           kramdown
highlighter:        rouge
paginate:           20
exclude:            [README.md]

baseurl:            /
domain_name:        'http://SH128.github.io'
url:                'http://SH128.github.io'
author:             'Stephanie Handsteiner'
authorTwitter:      'Steffi128_'
permalink:          /:year/:title/

defaults:
    -
        scope:
            path: ""
            type: pages
        values:
            layout: default
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: posts
