# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'stephfh.dev'
tagline:          'Full-Stack Developer'
description:      'A Full-Stack Web Developer from Europe.'
url:              https://stephfh.dev
baseurl:          /

author:
  name:           'Stephanie Handsteiner'
  url:            https://stephfh.dev

github:
  repo:           https://github.com/stephfh/stephfh.github.io
